name: Verification

on:
  push:
    branches: [main]
  pull_request_target:
  workflow_dispatch:

jobs:
  test:
    name: Test TypeScript
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout Project Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Use NodeJS LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install
        run: npm ci
      - name: Lint
        run: npm run check
      - name: Test
        run: npm run test:coverage
        env:
          CI: true
      - name: Send Coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: .coverage/lcov.info
          flags: unittests
          fail_ci_if_error: true
